code-push

diff --git a/.github/workflows/Frontend.yaml b/.github/workflows/Frontend.yaml
--- a/.github/workflows/Frontend.yaml
+++ b/.github/workflows/Frontend.yaml
@@ -5,7 +5,7 @@ on:
     branches: [ "main" ]
 
 jobs:
-  deploy:
+  build:
     runs-on: ubuntu-latest
 
     steps:
@@ -20,6 +20,24 @@ jobs:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1
+
+    # Run SonarQube Scan
+    - name: SonarQube Scan
+      uses: sonarsource/sonarqube-scan-action@v4
+      with:
+        args: -X -Dsonar.projectKey=Full-stack:Test    # Project name is Required 
+      env:
+        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
+
+    # Wait for SonarQube Quality Gate status
+    - name: Check SonarQube Quality Gate status
+      run: |
+        QUALITY_GATE_STATUS=$(curl -s -X GET -u ${{ secrets.SONAR_TOKEN }} "https://sonarcloud.io/api/qualitygates/project_status?projectKey=Full-stack:Test" | jq -r '.projectStatus.status')
+        if [[ "$QUALITY_GATE_STATUS" != "OK" ]]; then
+          echo "Quality Gate failed. Code not allowed to be pushed to ECR."
+          exit 1
+        fi
 
     # Login to Amazon ECR
     - name: Login to Amazon ECR
@@ -42,8 +60,6 @@ jobs:
         format: table
         severity: CRITICAL,HIGH
 
-
-        
     # Push Docker image to Amazon ECR
     - name: Push Docker Image to ECR
       run: docker push 761018870862.dkr.ecr.us-east-1.amazonaws.com/infosys:latest
